### ISSUE TITLE
[nodejs][51.cafe bot] Bot returns 'Refresh access token failed' trying to connect

### ISSUE THREAD

**Issue by joseques** [southworks/BotBuilder-Samples#103]
## Sample information
1. Sample type: \samples\
2. Sample language: nodejs
3. Sample name: 51.cafe-bot

## Describe the bug
After configuring the sample (using the workaround mentioned in Issue #102), run the `contoso-cafe-bot.bot` file with the Bot Framework Emulator, the bot returns instantly the error `Refresh access token failed with status code: 400` in the LOG window.

## To Reproduce
1. Follow the [README.md](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/51.cafe-bot/README.MD) installation instructions 
2. Follow the `Using MSBot CLI` route to create the required services and clone the bot
3. Apply the workaround mentioned in Issue #102 
4. Install modules and start the bot
5. Open the `.bot` file found in the sample folder with the Bot Framework Emulator
6. The bot returns the message `Refresh access token failed with status code: 400` in the LOG window.

## Expected behavior
The sample should run correctly.

[bug]

**Comment by enzocano** [comment]
This is an issue with the BotService itself. More Info: https://github.com/Microsoft/BotBuilder/issues/4432
