### ISSUE TITLE
[webapi][02.echo with counter] Sample crashes when running it

### ISSUE THREAD

**Issue by joseques** [southworks/BotBuilder-Samples#110]
## Sample information
1. Sample type: \samples\
2. Sample language: webapi
3. Sample name: 02.echo-with-counter

## Describe the bug
When running the sample, the following error gets thrown in the served page:
```
Could not find file 'C:\Users\username\Documents\Repos\BotBuilder-Samples\samples\csharp_webapi\13.Basic-Bot-Template\BasicBot.bot'. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileNotFoundException: Could not find file 'C:\Users\username\Documents\Repos\BotBuilder-Samples\samples\csharp_webapi\13.Basic-Bot-Template\BasicBot.bot'.

Source File: C:\Users\username\Documents\Repos\BotBuilder-Samples\samples\csharp_webapi\13.Basic-Bot-Template\App_Start\BotConfig.cs    Line: 34
```

## To Reproduce
_Since there's no README in the sample ( see #109 )_
1. Open the project
2. Build the solution
3. Run the project
4. See error in the served URL

## Expected behavior
Sample should run without any problems since there's no required services that should be deployed in order to work.

## Proposed solution
Change the endpoint configuration in the `.csproj` files to a unique port per sample. This change would require changing the `.bot` files endpoints too.

## Additional context
The `.csproj` files, seems to have the same endpoint configuration URL. Per example see [line 191](https://github.com/Microsoft/BotBuilder-Samples/blob/eeeee2e909da45096db9dba78c2cbc8fe67b9260/samples/csharp_webapi/02.echo-with-counter/EchoBot.csproj#L191) of the `EchoBot.csproj` file.
At the `EchoBot.csproj` file, the  `<WebProjectProperties>` is the same as the `BasicBot.csproj` file
```xml
<WebProjectProperties>
    <UseIIS>True</UseIIS>
    <AutoAssignPort>True</AutoAssignPort>
    <DevelopmentServerPort>2190</DevelopmentServerPort>
    <DevelopmentServerVPath>/</DevelopmentServerVPath>
    <IISUrl>http://localhost:3978/</IISUrl>
    <NTLMAuthentication>False</NTLMAuthentication>
    <UseCustomServer>False</UseCustomServer>
    <CustomServerUrl>
    </CustomServerUrl>
    <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
</WebProjectProperties>
```
When running a sample, all the endpoints in the solution get served in the IIS web servers thus overriding the last served page in the process and provoking unexpected behavior when running the samples.

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#744
