### ISSUE TITLE
[webapi][11.qnamaker] Prerequisite file cannot be imported to QnA Maker KB

### ISSUE THREAD

**Issue by joseques** [southworks/BotBuilder-Samples#115]
## Sample information
1. Sample type: \samples\
2. Sample language: webapi
3. Sample name: 11.qnamaker

## Describe the bug
Same error as Issue #74 
- [Step 2](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_webapi/11.QnAMaker#prerequisites) from `Prerequisites` in `readme.md` points to import a seemingly wrong file. The file [sample.qna](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_webapi/11.QnAMaker/CognitiveModels/sample.qna) can't be imported in the QnA Maker site

## To Reproduce
1. Follow the `Prerequisites` steps from `readme.md` [up to step 2](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_webapi/11.QnAMaker#prerequisites)
2. Import `sample.qna` to QnA portal
3. The following message will appear: `The file format is not supported for sample.qna. Incorrect file format. Import operation expects a .tsv file with question, answer, source and metadata fields.`

## Expected behavior
The steps in `prerequisites` should say to import a `.tsv` file. Said file should be present in the directory `\11.qnamaker\CognitiveModels\`. 

After importing the correct file, the Knowledge Base should be updated with the content of the file.

## Screenshots
This is the error that appears when trying to import the `.qna` to QnA portal.
![image](https://user-images.githubusercontent.com/39467613/46558459-8926cf00-c8c3-11e8-8440-6b7fc3e25fa8.png)

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#821
