### ISSUE TITLE
[netcore][51.cafe-bot] Bot is canceling current task anyway when choosing not to cancel the task

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#118]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **51.cafe-bot**

## Describe the bug
When canceling the booking of a table and the bot asks the user if they are use, if the user chooses `No`, the bot cancels the booking anyway.

## To Reproduce
1. Go to `...\BotBuilder-Samples-SW\samples\csharp_dotnetcore\51.cafe-bot`.
2. Open `CafeBot.sln`
3. Select and run `CafeBot` project
4. Open the bot in Bot Framework Emulator
5. Send `Book a table`
6. When the bot ask for what city, send `Cancel`
7. The bot will ask if you are sure, and two prompts to choose, `yes` and `no`. Choose `no`.
8. The boot will answer with `Sure. I've cancelled that!`

## Expected behavior
The bot should continue with the task previous the user sending the cancel command.

## Additional context
_In order to test this issue, the issue https://github.com/southworkscom/BotBuilder-Samples/issues/117 must be resolved beforehand._

This behavior happens because the [line 161](https://github.com/Microsoft/BotBuilder-Samples/blob/d04a523fe3f1dc6504d23016c5b4882bbe6a1d88/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/Prompts/GetLocationDateTimePartySizePrompt.cs#L161) of `GetLocationDateTimePartySizePrompt.cs`, `result` is being validate on if it is null or not; however, `result` is either `true` or `false` depending if the user chose to cancel or not, respectively.

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#844
