### ISSUE TITLE
[netcore][51.cafe-bot] UserSalutationAsync not working correctly

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#119]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **51.cafe-bot**

## Describe the bug
The method `_userProfileAccessor.GetAsync()` in [line 55](https://github.com/Microsoft/BotBuilder-Samples/blob/9720b4030954cd7d722a5e44f1a073a4a7d9c5f9/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/QnA/QnADialog.cs#L55) of file `QnADialog.cs` is missing a `defaultValueFactory`.

Also, the [line 56](https://github.com/Microsoft/BotBuilder-Samples/blob/9720b4030954cd7d722a5e44f1a073a4a7d9c5f9/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/QnA/QnADialog.cs#L56) of the same file has the validation for `userProfile` wrong.

## To Reproduce
1. Go to `...\BotBuilder-Samples-SW\samples\csharp_dotnetcore\51.cafe-bot`.
2. Open `CafeBot.sln`
3. Select and run `CafeBot` project
4. Open the bot in Bot Framework Emulator
5. Send `Hi`
6. The bot will answer with `Sorry, it looks like something went wrong`

## Expected behavior
The bot should reply with a greeting.

## Additional context
The following code is a workaround for the [line 55](https://github.com/Microsoft/BotBuilder-Samples/blob/9720b4030954cd7d722a5e44f1a073a4a7d9c5f9/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/QnA/QnADialog.cs#L55):
```c#
var userProfile = await _userProfileAccessor.GetAsync(context, () => null);
```

The following code is a workaround for the [line 56](https://github.com/Microsoft/BotBuilder-Samples/blob/9720b4030954cd7d722a5e44f1a073a4a7d9c5f9/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/QnA/QnADialog.cs#L56):
```c#
if (userProfile != null && !string.IsNullOrWhiteSpace(userProfile.UserName))
{
	...
}
```
For this last snippet, refer to the [same implementation in NodeJS](https://github.com/Microsoft/BotBuilder-Samples/blob/d04a523fe3f1dc6504d23016c5b4882bbe6a1d88/samples/javascript_nodejs/51.cafe-bot/dialogs/qna/index.js#L72).

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#849
