### ISSUE TITLE
[netcore][51.cafe-bot] Cafe Bot is not behaving as expected after greeting

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#120]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **51.cafe-bot**

## Describe the bug
The bot can not set the state of gathered properties after being greeted (please see Issue https://github.com/southworkscom/BotBuilder-Samples/issues/119 for a related issue).

## To Reproduce
1. Go to `...\BotBuilder-Samples-SW\samples\csharp_dotnetcore\51.cafe-bot`.
2. Open `CafeBot.sln`
3. Select and run `CafeBot` project
4. Open the bot in Bot Framework Emulator
5. Send `Hi`
6. The bot will reply with `Hi! Is there anything else I can help you with?`
7. Either choose or send `Book a Table`
8. The bot will reply with `Sorry, it looks like something went wrong`

## Expected behavior
The bot should ask for the city where to book the table, as it does when `Book a Table` is sent without a previous greeting.

## Screenshots
The following gif shows first how the `Book_Table` intent works without a previous greeting, then the same message is sent but after greeting the bot.
<img src="https://user-images.githubusercontent.com/39467613/47091871-1f2ff300-d1fc-11e8-94d5-d3789fe93bb2.gif" width="395">

## Additional context
The problem originates in [line 135](https://github.com/Microsoft/BotBuilder-Samples/blob/e2c6be7333cc2a9d4ba85f8f820f138e10dd8732/samples/csharp_dotnetcore/51.cafe-bot/CafeBot.cs#L135) of `CafeBot.cs`, when the `_onTurnAccessor.SetAsync(context, onTurnProperties)` is called after a greeting it throws the following exception:
```
The value was of an incorrect type for this dictionary.
```

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#850
