### ISSUE TITLE
[netcore][51.cafe-bot] ReservationProperty.cs readonly properties not assigned correctly

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#121]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **51.cafe-bot**

## Describe the bug
The bot throws an exception when trying to parse the city entity.

## To Reproduce
1. Go to `...\BotBuilder-Samples-SW\samples\csharp_dotnetcore\51.cafe-bot`.
2. Open `CafeBot.sln`
3. Select and run `CafeBot` project
4. Open the bot in Bot Framework Emulator
5. Send `Book a Table`
6. The bot will send `What city?`
7. Send `Seattle`
8. The bot will reply with `Sorry, it looks like something went wrong`

## Expected behavior
The bot should ask for the date in step 8

## Additional context
The exception throw occurs in [line 105](https://github.com/Microsoft/BotBuilder-Samples/blob/e2c6be7333cc2a9d4ba85f8f820f138e10dd8732/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/StateProperties/ReservationProperty.cs#L105) of file `ReservationProperty.cs`, since the variable is not set.

However, the error originates from [line 12 to line 20](https://github.com/Microsoft/BotBuilder-Samples/blob/e2c6be7333cc2a9d4ba85f8f820f138e10dd8732/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/StateProperties/ReservationProperty.cs#L12-L20) of the same file.
Multiple read-only variables are being assigned using `luisEntities[]` array, however, the array is being initialised _after_ the assignation of the read-only variables.

A workaround for this is to move the `luisEntities[]` array initialisation before the assgination of the read-only variables, or assign literal strings to the read-only variables.

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#852
