### ISSUE TITLE
[netcore][51.cafe-bot] Bot throws an exception when providing a city name

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#122]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **51.cafe-bot**

## Describe the bug
After fixing/applying the workaround descripted in issue https://github.com/southworkscom/BotBuilder-Samples/issues/121, replying with `Seattle` after being prompted for a city an exception is thrown.

## To Reproduce
1. Go to `...\BotBuilder-Samples-SW\samples\csharp_dotnetcore\51.cafe-bot`.
2. Open `CafeBot.sln`
3. Select and run `CafeBot` project
4. Open the bot in Bot Framework Emulator
5. Send `Book a Table`
6. The bot will send `What city?`
7. Send `Seattle`
8. The bot will reply with `Sorry, it looks like something went wrong`

## Expected behavior
The bot should store the city and ask for the date in step 8

## Additional context
The problem seems to reside in the [line 186](https://github.com/Microsoft/BotBuilder-Samples/blob/70c44932e1ab3b453410599df1bf0be3b5b03935/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/StateProperties/ReservationProperty.cs#L186) of the file `ReservationProperty.cs`.
The exepction says that can not convert `string` to `JObject`.
```C#
 if (locationEntity != null)
 {
	 var cafeLocation = ((JObject)locationEntity.Value)[0][0];

	 // Capitalize cafe location.
	 returnResult.NewReservation.Location = char.ToUpper(((string)cafeLocation)[0]) + ((string)cafeLocation).Substring(1);
 }
```
Looking closely at `locationEntity.Value`, it is simply an string value ([line 107](https://github.com/Microsoft/BotBuilder-Samples/blob/70c44932e1ab3b453410599df1bf0be3b5b03935/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/StateProperties/ReservationProperty.cs#L107)), therefore it is not necesary to cast it as JObject in line 186 and then cast it again as string in line 189.

It is advisable to either remove the casting to JObject, or remove the `cafeLocation` variable and simply use `location.Entity.Value` in line [line 189](https://github.com/Microsoft/BotBuilder-Samples/blob/70c44932e1ab3b453410599df1bf0be3b5b03935/samples/csharp_dotnetcore/51.cafe-bot/Dialogs/Shared/StateProperties/ReservationProperty.cs#L189).

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#853
