### ISSUE TITLE
[netcore] Validate the existence of file before loading them

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#126]
**Is your feature request related to a problem? Please describe.**
At the present time, the samples are loading `.bot` files without validing if they exist or have the right name, leading to unhandled exceptions.

**Describe the solution you'd like**
Before loading a bot file, validate its existence with `File.Exist(botFilePath)` or enclosing the code block with a `try-catch`.

**Additional context**
While this is a general feature request for all the samples, an issue was opened for a specific sample: issue https://github.com/southworkscom/BotBuilder-Samples/issues/83.

Additionally, in the case of the samples for NodeJS, all the [index.js](https://github.com/Microsoft/BotBuilder-Samples/blob/70eb9862b0794c67583c01758bf387bed0c13f0e/samples/javascript_nodejs/10.prompt-validations/index.js#L31) contemplate this possibility.

[enhancement]

**Comment by dfavretto** [comment]
Closed due to Microsoft#730
