### ISSUE TITLE
[netcore][12.nlp-with-luis] Missing .luis file, recipe missing LUIS service

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#132]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **12.nlp-with-luis**

## Describe the bug
The LUIS services is missing from the [bot recipe](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/12.nlp-with-luis/DeploymentScripts/MsbotClone/bot.recipe) file.
Also, the `.luis` file is missing from the folder.

## To Reproduce
1. Follow the steps in the read me to [Deploy to Azure](https://github.com/Microsoft/BotBuilder-Samples/blob/3ebca19a901ecfe3433b3660f0ed05f517a937d2/samples/csharp_dotnetcore/12.nlp-with-luis/README.md#deploy-this-bot-to-azure)
2. A `.bot` file will be generated
3. Said bot configuration file will be missing the LUIS service

## Expected behavior
The `bot.recipe` should include the LUIS service and the folder shoud include the `.luis` file, so when it is deployed to Azure and the `BotConfiguration.bot` is created, it will contain the LUIS service.

## Additional context
The example for NodeJS include both the [.luis file](https://github.com/Microsoft/BotBuilder-Samples/blob/3ebca19a901ecfe3433b3660f0ed05f517a937d2/samples/javascript_nodejs/12.nlp-with-luis/deploymentScripts/msbotClone/34.luis) and the [bot.recipe](https://github.com/Microsoft/BotBuilder-Samples/blob/3ebca19a901ecfe3433b3660f0ed05f517a937d2/samples/javascript_nodejs/12.nlp-with-luis/deploymentScripts/msbotClone/bot.recipe) with the luis service included.

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#814
