### ISSUE TITLE
Samples are missing a section on how to interact with the bot

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#136]
**Is your feature request related to a problem? Please describe.**
Most samples readme are missing a short description on how to interact with the bot or what to expect from the bot.

**Describe the solution you'd like**
A new `Testing the Bot` section should be included in the readme explaining how to interact with the bot once its running, and/or what to expect from the bot once it is running.

**Describe alternatives you've considered**
An alternative to the creation of a new section is to add the description at the bottom of `Connect to bot using Bot Framework Emulator` section.

**Additional context**
[Sample #01](https://github.com/Microsoft/BotBuilder-Samples/tree/0492c45717fcb3033106572e8a1e55870414241f/samples/javascript_nodejs/01.console-echo#testing-the-bot) for NodeJS is one of the few readmes that contain a brief description on how to interact with the bot.

[enhancement]

**Comment by joseques** [comment]
👍

**Comment by dfavretto** [comment]
Readmes are being redesigned by MS.
