### ISSUE TITLE
[DotNet][Samples] Missing instructions for deploying EchoBot to Azure

### ISSUE THREAD

**Issue by ParadoxARG** [southworks/BotBuilder-Samples#168]
## Sample information
1. Sample type: Samples
2. Sample language: DotNetCore
3. Sample name: EchoBot

## Describe the bug
There is an instruction and a parameter missing for deploying the bot to Azure.

## To Reproduce
1. Follow the [Readme](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/02.a.echo-bot/README.md) "Deploy the bot to Azure" instructions

## Expected behavior
It should deploy the bot to Azure and create all the necesary resources

## Screenshots
![image](https://user-images.githubusercontent.com/42191764/52482858-2440f580-2b91-11e9-9f5c-305255965df8.png)
![image](https://user-images.githubusercontent.com/42191764/52482891-36229880-2b91-11e9-8d8f-0b682ab5f6da.png)

## Proposed Solution
For the user-secrets issue we could add a `<UserSecretsId></UserSecretsId>` placeholder in `EchoBot.csproj` and explain in the Readme that this should be modified.

Also, for the bot publish issue, we should add to the Readme deploy command the `--proj-file "EchoBot.csproj"` parameter.

**Comment by VictorGrycuk** [comment]
On _Proposed Solution_ section, there are two `add`.

**Comment by ParadoxARG** [comment]
> On _Proposed Solution_ section, there are two `add`.

Fixed

**Comment by VictorGrycuk** [comment]
LGTM! :shipit:

**Comment by JuanAr** [comment]
🚢 
@denscollo can you review and promote to the MS repo?

**Comment by denscollo** [comment]
Sure, will do it now!

**Comment by denscollo** [comment]
Replaced by #1214
