### ISSUE TITLE
[Generators][Linux] Dependencies issue when deploying with netcoreapp 2.1

### ISSUE THREAD

**Issue by ParadoxARG** [southworks/BotBuilder-Samples#186]
## Sample information
1. Sample type: \generators\
2. Sample language: dotnetcore - netcoreapp2.1
3. Sample name: EchoBot

## Describe the bug
The generated EchoBot for NetCoreApp has some conflicts in the references. In consequence, it fails when trying to deploy it to an Azure Linux Host using netcoreapp2.1.

Conflicting references:
- Microsoft.Bot.Builder.Integration.AspNet.Core 4.4.3 and Microsoft.AspNetCore.App 2.1.0.
For all the following libraries Microsoft.Bot.Builder.Integration.AspNet.Core requires a version >= 2.1.1 and Microsoft.AspNetCore.App requires version 2.1.0
    - Microsoft.Extensions.Configuration
    - Microsoft.Extensions.Configuration.Abstractions
    - Microsoft.Extensions.Configuration.Binder
    - Microsoft.Extensions.DependencyInjection.Abstractions
    - Microsoft.Extensions.Logging
    - Microsoft.Extensions.Logging.Abstractions
    - Microsoft.Extensions.Options
    - Microsoft.Extensions.Primitives

## To Reproduce
1. Install EchoBot template

```bash
# Install EchoBot template
dotnet new -i Microsoft.Bot.Framework.CSharp.EchoBot
```

2. Generate an EchoBot with netcoreapp2.1 as the targeted framework

```bash
# Generate an Echo Bot (netcoreapp2.1)
dotnet new echobot --framework netcoreapp2.1 -n MyEchoBot
```

3. Deploy the bot with git to your Azure webapp hosted in linux with netcoreapp2.1([guide for setting up the linux host](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-dotnetcore))

![image](https://user-images.githubusercontent.com/42191764/58105654-3e8d6500-7bbd-11e9-8961-af933fcb97f8.png)

## Expected behavior
The bot should be deployed without errors

[bug]

**Comment by denscollo** [comment]
LGTM :shipit:

**Comment by gasper-az** [comment]
LGTM

**Comment by ParadoxARG** [comment]
Replaced by [#1524](https://github.com/microsoft/BotBuilder-Samples/issues/1524)
