### ISSUE TITLE
[netcore][11.qnamaker] Missing files and Readme has wrong instruction

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#74]
## Sample information
1. Sample type: [\samples\]
2. Sample language: [dotnetcore]
3. Sample name: 11.qnamaker

## Describe the bug
- The `bot.recipe` is missing the resource `qna`.
  - `BotConfiguration.bot` is missing the `qna` service
- Step 2 from `Prerequisites` in `readme.md` points to import the [wrong archive](https://github.com/Microsoft/BotBuilder-Samples/blame/db817c5bb0ed0d2cb15f17ae65ca54a67d580c75/samples/csharp_dotnetcore/11.qnamaker/README.md#L20)
- File `smartLightFAQ.tsv` missing from directory `\11.qnamaker\CognitiveModels\`
- File `34.qna` missing from directory `\11.qnamaker\deploymentScripts\msbotClone`

## To Reproduce
1. Follow the `Prerequisites` steps from `readme.md` [up to step 2](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/11.qnamaker/README.md#prerequisites)
2. Import `sample.qna` to QnA portal
3. The following message will appear: `The file format is not supported for sample.qna. Incorrect file format. Import operation expects a .tsv file with question, answer, source and metadata fields.`

## Expected behavior
The steps in `prerequisites` should say to import a `.tsv` file. Said file should be present in the directory `\11.qnamaker\CognitiveModels\`. 

After importing the correct file, the Knowledge Base should be updated with the content of the file.

Additionally, following the steps in the `readme.md` the `BotConfiguration.bot` should have the corresponding properties to update with the QnA information.

## Screenshots
This is the error that appears when trying to import the `.qna` to QnA portal.
![image](https://user-images.githubusercontent.com/39467613/46558459-8926cf00-c8c3-11e8-8440-6b7fc3e25fa8.png)

The file on the left shows the content of the `bot.recipe` of sample # 11, the file on the right shows the how the bot.recipe should have (taken from the same sample but for JavaScript).
![image](https://user-images.githubusercontent.com/39467613/46558474-9479fa80-c8c3-11e8-9ccc-1b1cf0eec306.png)

**Comment by dfavretto** [comment]
Closed due to Microsoft#628
