### ISSUE TITLE
[netcore][17.multilingual-bot] Code points to non-existent/misnamed file

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#83]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **17.multilingual-bot**

## Describe the bug
In file `Startup.cs` [line 63](https://github.com/Microsoft/BotBuilder-Samples/blob/70eb9862b0794c67583c01758bf387bed0c13f0e/samples/csharp_dotnetcore/17.multilingual-bot/Startup.cs#L63), the code points to a `BotConfiguration.bot` file, however, the actual file name is [MultiLingualBot.bot](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/17.multilingual-bot/MultiLingualBot.bot).

## To Reproduce
1. Go to `botbuilder-samples/samples/csharp_dotnetcore/17.multilingual-bot`
2. Open the project `MultiLingualBot.csproj`
3. Select and run `MultiLingualBot` project
4. After running the project a `System.IO.FileNotFoundException` will be thrown saying that the file `BotConfiguration.bot` could not be found.

## Expected behavior
The file `MultiLingualBot.bot` should be renamed to `BotConfiguration.bot`, then the information stored in said  file should be imported when running the `MultiLingualBot` project.

An alternative could be changing the line [line 63](https://github.com/Microsoft/BotBuilder-Samples/blob/70eb9862b0794c67583c01758bf387bed0c13f0e/samples/csharp_dotnetcore/17.multilingual-bot/Startup.cs#L63) to point to the file [MultiLingualBot.bot](https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/17.multilingual-bot/MultiLingualBot.bot).

## Screenshots
![image](https://user-images.githubusercontent.com/39467613/46672184-25dfba00-cbad-11e8-8f29-e2389911a93c.png)

[bug]

**Comment by dfavretto** [comment]
Closed due to #126
