### ISSUE TITLE
[netcore][21.luis-with-appinsights] LuisApplication is getting as argument 'region' instead of 'endpoint'

### ISSUE THREAD

**Issue by VictorGrycuk** [southworks/BotBuilder-Samples#89]
## Sample information
1. Sample type: **[\samples\\]**
2. Sample language: **[dotnetcore]**
3. Sample name: **21.luis-with-appinsights**

## Describe the bug
In [Line 178](https://github.com/Microsoft/BotBuilder-Samples/blob/995219f8ff8fa4eaf4359c2af8db5fc290a3295c/samples/csharp_dotnetcore/21.luis-with-appinsights/Startup.cs#L178) of `Startup.cs`, a new `LuisApplication` is being initialized. However, the `region` is being used as argument instead of `endpoint`.
This gives as result an exception message saying `{region} is not a valid LUIS endpoint`.

## To Reproduce
1. Go to `botbuilder-samples/samples/csharp_dotnetcore/21.luis-with-appinsights`
2. Configure `BotConfiguration.bot` with the required fields
3. Open the project `LuisBotAppInsights.csproj`
4. Select and run `LuisBotAppInsights` project
5. After trying to interact with the bot, an exception will be thrown saying that the specified region is not a valid LUIS endpoint.

## Expected behavior
The bot should work with the endpoint configured in `BotConfiguration.bot`.

## Screenshots
![image](https://user-images.githubusercontent.com/39467613/46691178-a49f1c00-cbda-11e8-984e-21c534da65de.png)

[bug]

**Comment by dfavretto** [comment]
Closed due to Microsoft#711
