### ISSUE TITLE
[nodejs][09.message-routing] Sample crashes after receiving greeting

### ISSUE THREAD

**Issue by joseques** [southworks/BotBuilder-Samples#97]
## Sample information
1. Sample type: \samples\ 
2. Sample language: nodejs
3. Sample name: 09.message-routing

## Describe the bug
The sample runs smoothly, responds as it should when a message containing `help` or `cancel` is received by the user but when a greeting is received, the sample throw the following error
```
[onTurnError]: TypeError: Cannot read property 'options' of undefined
(node:6528) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revoked
    at adapter.sendActivities.then (C:\Users\username\Documents\Repos\BotBuilder-Samples\samples\javascript_nodejs\09.message-routing\node_modules\botbuilder-core\lib\turnContext.js:175:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce
1. Follow the installation instructions in the [README](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/09.message-routing)
2. Run the bot with the Bot Framework Emulator
3. Send 'Hello' to the bot
4. See the error `[onTurnError]: TypeError: Cannot read property 'options' of undefined`

## Expected behavior
After sending 'Hello', the bot should ask the user for it's name and city and keep running without interruptions.

[bug]

**Comment by enzocano** [comment]
Fixed with PR.721
