### ISSUE TITLE
[nodejs][50.diceroller-skill] Missing .env file in sample

### ISSUE THREAD

**Issue by joseques** [southworks/BotBuilder-Samples#99]
## Sample information
1. Sample type: \samples\
2. Sample language: nodejs
3. Sample name: 50.diceroller-skill

## Describe the bug
The sample lacks the `.env` and can't be run without adding it manually. The [README](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/50.diceroller-skill) doesn't mentions the addition of the beforementioned file.

## Additional Context
The sample fallbacks to a default `cortana-skill.bot` bot file in case the `botFileSecret` is not defined in the `.env` file. This filename is wrong and doesn't exists in the sample folder.

[bug]

**Comment by enzocano** [comment]
Already reported Issue.682
